### ISSUE TITLE
Limit checks on WfmData-SP

### ISSUE THREAD

**Issue by xresende** [lnls-sirius/dev-packages#21]
at this point we are not performing limit checks on wfmdata at high level classes (MAEpics, PowerSupply, ControllerIOC). we have to implement it! thanks, @fernandohds564 , for pointing this out!

**Comment by xresende** [comment]
current pcaspy version seems to be doing a bogous comparison of the waveform with the PV limit, if it is defined. An issue (paulscherrerinstitute/pcaspy#52) about this was created and solutions are being discussed.

**Comment by fernandohds564** [comment]
The issue referred in the last comment was closed. The current version of pcaspy checks the limits of the waveform PV and raises an alarm when at least one of its elements is outside the defined boundaries.

**Comment by xresende** [comment]
deprecated
