### ISSUE TITLE
Limits in simulation of Low Level Timing modules

### ISSUE THREAD

**Issue by fernandohds564** [lnls-sirius/dev-packages#43]
The Low Level timing modules provide PVs of type unsigned integer of 32 bits for delays and widths of the trigger pulses. This type of PV is not supported in pcaspy, so I changed the limits of the PVs in simulation from 2**32-1 to 2*31-1.

An issue was created in https://github.com/paulscherrerinstitute/pcaspy/issues/53 to check the possibility of creating this data type in pcaspy.

**Comment by xresende** [comment]
@fernandohds564 , isn't this issue solved already?

**Comment by fernandohds564** [comment]
yes, it is. Sorry @xresende.
